env:
  browser: true
  es2020: true
extends:
  - airbnb
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
rules:
  semi: 0
  react/jsx-filename-extension: 0
  react/prefer-stateless-function: 1
  react/prop-types: 0
  react/no-array-index-key: 1
  react/forbid-prop-types: 1
  react/jsx-props-no-spreading: 1
  react/state-in-constructor: 0
  no-param-reassign: 0
  no-use-before-define: 1
  no-await-in-loop: 1
  import/no-cycle: 1
  import/no-unresolved: 1
  max-len: 0
  no-restricted-syntax: 0
settings:
  import/resolver:
    node:
      paths:
        - src
